theme: jekyll-theme-minimal
title: Proactive management of mobility impact of interdependent subsurface utility and roadway construction through incentives
description: Data sharing
markdown: kramdown
github:
  is_project_page: false
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji