theme: jekyll-theme-minimal
title: Data sharing
description: Proactive management of mobility impact of interdependent subsurface utility and roadway construction through incentives
markdown: kramdown
github:
  is_project_page: false
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji